version: "3"

services: 
    back:
          container_name: backweb
          restart: always
          build: ./backend
          volumes: 
              - ./backend:/app
              - node_modules:/app/node_modules
          environment: 
              - PORT
          ports: 
              - ${PORT}:${PORT}

    front:
          container_name: frontweb
          restart: always
          build: ./crud
          ports:  
              - 3000:3000
          volumes: 
              - ./crud:/app
              - node_modulesr:/app/node_modules
          environment: 
              - REACT_APP_URL_BACK
          links: 
              - back

volumes: 
    node_modules:
    node_modulesr:

         
          
    