version: "3"

services: 
    back:
          container_name: backweb
          restart: always
          build: ./backend
          ports: 
              - ${PORT}:${PORT}
          volumes: 
              - ./backend:/usr/src/app
          environment: 
              - PORT
    front:
          container_name: frontweb
          restart: always
          build: ./frontend/crud-sockets
          ports:  
              - 3000:3000
          volumes: 
              - ./frontend/crud-sockets:/usr/src/app
          environment: 
              - REACT_APP_URL_BACK
          links: 
              - back